// <auto-generated />
using System;
using INF27507_Boutique_En_Ligne;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INF27507_Boutique_En_Ligne.Migrations
{
    [DbContext(typeof(BoutiqueDbContext))]
    [Migration("20220219180103_Initial_migration")]
    partial class Initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_carts_id");

                    b.HasIndex("ClientId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_cartitems_id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_categories_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manteaux"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pantalons"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chemises"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chaussures"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accessoires"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_clients_id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_orders_id");

                    b.HasIndex("CartId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_products_id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "The North Face au 31\nC'est le parka utilitaire performant pour affronter les temps froids de ville\nChaude isolation en duvet d'oie 550 idéale pour les températures froides\nCoquille Dryvent imperméable et respirante assurant un confort au sec\nCapuchon tempête bordé aspect fourrure amovible\nFermoir zip aller - retour sous patte pression\nPoches pratiques",
                            Image = "wwwroot/img/manteaux_parka_duvet_mcmurdo.jpg",
                            Price = 299.94999999999999,
                            SellerId = 1,
                            ShortDescription = "",
                            Title = "Le parka duvet McMurdo"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Description = "Un denim joggjean tissé effet tricot au pigment bleu délavé pour un confort décontracté ultra extensible\nNotre coupe nommée Stockholm désigne un pantalon à jambe étroite et à taille régulière\nModèle 5 poches\nCoton extensible tout confort",
                            Image = "wwwroot/img/jean_tricot_bleu_coupe_stockholm.jpg",
                            Price = 89.0,
                            SellerId = 1,
                            ShortDescription = "",
                            Title = "Le jean tricot bleu délavé Coupe Stockholm - étroite"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Description = "Vans chez Simons\nCollection MTEMC toutes saisons\nMTE Snow : sous la neige\nPratiques, compressibles et prêtes à sortir en ville, le modèle Standard Mid Snow MTE est une version réduite de la populaire botte d'hiver du même nom. Enfin une chaussure qui fusionne le style classique de Vans aux besoins utilitaires du quotidien!\nTige imperméable en cuir véritable\nConstruction étanche aux coutures scellées\nChaude et douce doublure coussinée avec isolation de 100 g\nSemelle intérieure coussinée amovible\nGanse arrière pour faciliter le chaussage\nCoque de protection en caoutchouc vulcanisé\nSemelle extérieure en caoutchouc Snow MTE à crans dynamiques qui garantissent une adhérence et une flexibilité fiables sur tous les terrains et dans toutes les conditions\nNuméro de modèle : VN0A54FUY28",
                            Image = "wwwroot/img/sneaker_hiver_mid_mte_snow.jpg",
                            Price = 129.94999999999999,
                            SellerId = 1,
                            ShortDescription = "",
                            Title = "Le sneaker d'hiver Standard Mid MTE Snow"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_sellers_id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Default",
                            Lastname = "Seller",
                            Username = "default-seller"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Cart", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Client", "Client")
                        .WithMany("Carts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.CartItem", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Order", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Product", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Client", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Seller", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
